[package]
org = "ballerina"
name = "yaml"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["yaml"]
repository = "https://github.com/ballerina-platform/module-ballerina-yaml"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241007-143200-6b69ca80"
